<tr>
    <td>{{$user->id}}</td>
    <td>{{$user->name}}</td>
    <td>{{$user->email}}</td>
    <td>{{$user->email_verified_at}}</td>
    <td>{{$user->password}}</td>
    <td>{{$user->profile_photo_path}}</td>
    <td>{{$user->created_at}}</td>
    <td>{{$user->update_at}}</td>
</tr>
